version: '1.0'
name: go
displayName: go
triggers:
  trigger: auto
  pr:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@golang
        name: Test
        displayName: Golang 测试
        golangVersion: '1.8'
        commands:
          - go env -w GO111MODULE=on
          - go env -w GOPROXY=https://goproxy.cn,direct
          - go test -v ./...
        notify: []
permissions:
  - role: admin
    members: []
